### ISSUE TITLE
Header and Standard format

### ISSUE THREAD

**Issue by nsankar** [cpflat/log2seq#2]
@cpflat  Thanks for developing this great library. 

I have running log lines from a IOT device like the below one as an example

{"msg":"","time":"2022-02-15T16:07:19.40208293Z","log":"18:02:18.302 [| producer-1] INFO  k.l.p.p.service.kinesis.Kinesis -  SEND: topic=data.acm.json.telemetry partition=14 offset=11345632 msg={\"KIN\":\"1CCCRT\",\"Tyre\":{\"Received\":\"2022-02-15T16:06:26Z\",\"Level\":48.1,\"U\n","stream":"stdout"}

I get a header mismatch error when I used this log line to test
![image](https://user-images.githubusercontent.com/431890/155740902-201bbe4a-9d25-4d41-b9a9-fca12f619638.png)

How should I specify the header format for this? I went through your test code, but didn't understand this properly. If you can share a sample code for this, it will greatly help understand. Thank you in advance.

**Comment by cpflat** [comment]
Hi @nsankar.

The default parser of log2seq is designed for Syslog-like messages, so you need a customized parser for the message.
As the message has broken parenthesis pairs, it is difficult to strictly parse the message.
So I just tried to parse (first) timestamp and others in the message.

Please use log2seq>=0.2.6 to test the script, as the previous versions have a bug in parsing ISO8601 timestamps.

```
from log2seq import LogParser
from log2seq import preset
from log2seq.header import *
from log2seq.statement import *


text = """{"msg":"","time":"2022-02-15T16:07:19.40208293Z","log":"18:02:18.302 [| producer-1] INFO k.l.p.p.service.kinesis.Kinesis - SEND: topic=data.acm.json.telemetry partition=14 offset=11345632 msg={"KIN":"1CCCRT","Tyre":{"Received":"2022-02-15T16:06:26Z","Level":48.1,"U\\n","stream":"stdout"}"""

header_rules = [
        DatetimeISOFormat(),
        Statement()
]
full_format = "{\"msg\":\"\",\"time\":\"<0>\",\"log\":\"<1>\"}"
header_parser = HeaderParser(header_rules, full_format=full_format)

pattern_isotime = re.compile((r'^(\d{4})-(\d{2})-(\d{2})T'
                              r'(\d{2}):(\d{2}):(\d{2})'
                              r'(\.\d+)?'
                              r'(Z|([+-](\d{2})\:(\d{2})))?$'))
pattern_time = re.compile(r'^(\d{2}):(\d{2}):(\d{2})(\.\d+)?$')

statement_rules = [
    Split('"' + "()[]{}|+',=><;`# "),
    Fix([pattern_isotime, pattern_time]),
    Split(":"),
]
statement_parser = StatementParser(statement_rules)

parser = LogParser(header_parser, statement_parser)

parsed_line = parser.process_line(text)
timestamp = parsed_line["timestamp"]
print(f"timestamp: {timestamp}")
words = parsed_line["words"]
print(f"words: {words}")
```

This code will output: 
```
timestamp: 2022-02-15 16:07:19.402082+00:00
words: ['18:02:18.302', 'producer-1', 'INFO', 'k.l.p.p.service.kinesis.Kinesis', '-', 'SEND', 'topic', 'data.acm.json.telemetry', 'partition', '14', 'offset', '11345632', 'msg', 'KIN', '1CCCRT', 'Tyre', 'Received', '2022-02-15T16:06:26Z', 'Level', '48.1', 'U\\n', 'stream', 'stdout']
```

Does it help you?
You may need to modify statement_rules considering the other messages for parsing.

**Comment by nsankar** [comment]
Thank you @cpflat .  let me go through this and understand. 

What does <0> and <1> signify?

This should greatly help.

Also I found Drain3 template and parameter extraction much easier using masking in its config. Perhaps adding Drain3 as an option in log2seq.might help enable unsupervised parsing and extraction.? Any thoughts on this?

**Comment by cpflat** [comment]
> What does <0> and <1> signify?

They correspond to the index of header_rules.
In this case, <0> is the timestamp part and <1> is the statement part (message strings for word segmentation).
See [Documentation](https://log2seq.readthedocs.io/en/latest/ref_header.html) for more details.

> Also I found Drain3 template and parameter extraction much easier using masking in its config. Perhaps adding Drain3 as an option in log2seq.might help enable unsupervised parsing and extraction.? Any thoughts on this?

I believe [amulog](https://github.com/amulog/amulog) is the exact tool you need.
Amulog classifies log messages, parsed with log2seq, by their automatically-generated log templates. 
It supports Drain as a log template generation algorithm.
Please check it.

**Comment by nsankar** [comment]
@cpflat  Appreciate your help and inputs. Will check out amulog
